anchor_version = "0.18.2"

[workspace]
members = [
    ".",
]

[provider]
cluster = "localnet"
wallet = "~/.config/safecoin/id.json"

[programs.mainnet]
serum_dex = "SRMrEgnzRgGMQ8QzcL8cjWr5xpdVs1KQCQ58Jkkq1qx"
